# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shop-app-prisma-sqlite"
client_id = "66e2134e0f0e2e1237d986742ee0e6bc"
application_url = "https://humane-fly-tops.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://humane-fly-tops.ngrok-free.app/auth/callback",
  "https://humane-fly-tops.ngrok-free.app/auth/shopify/callback",
  "https://humane-fly-tops.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "crptest3.myshopify.com"
